import { LookupCatalogConfig } from './lookup-catalog.models';

/** Un registro por cada tabla pequeña de catálogo que hoy solo se consumía como
 * dropdown (via CatalogService) y no tenía ninguna pantalla de administración —
 * el backend ya expone CRUD completo para todas, solo faltaba el frontend. */
export const LOOKUP_CATALOG_CONFIGS: Record<string, LookupCatalogConfig> = {
  countries: {
    slug: 'countries',
    resource: 'Countries',
    idField: 'countryId',
    titleKey: 'lookupCatalogs.countries.title',
    hasCode: false,
    hasIsActive: false,
    hasAddress: false,
    nameMaxLength: 100,
  },
  'document-types': {
    slug: 'document-types',
    resource: 'DocumentTypes',
    idField: 'documentTypeId',
    titleKey: 'lookupCatalogs.documentTypes.title',
    hasCode: false,
    hasIsActive: false,
    hasAddress: false,
    nameMaxLength: 50,
  },
  'church-types': {
    slug: 'church-types',
    resource: 'ChurchTypes',
    idField: 'churchTypeId',
    titleKey: 'lookupCatalogs.churchTypes.title',
    hasCode: false,
    hasIsActive: false,
    hasAddress: false,
    nameMaxLength: 50,
  },
  'print-types': {
    slug: 'print-types',
    resource: 'PrintTypes',
    idField: 'printTypeId',
    titleKey: 'lookupCatalogs.printTypes.title',
    hasCode: false,
    hasIsActive: false,
    hasAddress: false,
    nameMaxLength: 50,
  },
  'issue-types': {
    slug: 'issue-types',
    resource: 'IssueTypes',
    idField: 'issueTypeId',
    titleKey: 'lookupCatalogs.issueTypes.title',
    hasCode: false,
    hasIsActive: true,
    hasAddress: false,
    nameMaxLength: 50,
  },
  'receipt-types': {
    slug: 'receipt-types',
    resource: 'ReceiptTypes',
    idField: 'receiptTypeId',
    titleKey: 'lookupCatalogs.receiptTypes.title',
    hasCode: false,
    hasIsActive: true,
    hasAddress: false,
    nameMaxLength: 50,
  },
  'media-types': {
    slug: 'media-types',
    resource: 'MediaTypes',
    idField: 'mediaTypeId',
    titleKey: 'lookupCatalogs.mediaTypes.title',
    hasCode: false,
    hasIsActive: true,
    hasAddress: false,
    nameMaxLength: 50,
  },
  departments: {
    slug: 'departments',
    resource: 'Departments',
    idField: 'departmentId',
    titleKey: 'lookupCatalogs.departments.title',
    hasCode: false,
    hasIsActive: true,
    hasAddress: false,
    nameMaxLength: 100,
  },
  'sub-departments': {
    slug: 'sub-departments',
    resource: 'SubDepartments',
    idField: 'subDepartmentId',
    titleKey: 'lookupCatalogs.subDepartments.title',
    hasCode: false,
    hasIsActive: true,
    hasAddress: false,
    nameMaxLength: 100,
  },
  missions: {
    slug: 'missions',
    resource: 'Missions',
    idField: 'missionId',
    titleKey: 'lookupCatalogs.missions.title',
    hasCode: false,
    hasIsActive: true,
    hasAddress: false,
    nameMaxLength: 100,
  },
  provinces: {
    slug: 'provinces',
    resource: 'Provinces',
    idField: 'provinceId',
    titleKey: 'lookupCatalogs.provinces.title',
    hasCode: false,
    hasIsActive: true,
    hasAddress: false,
    nameMaxLength: 100,
  },
  'special-cases': {
    slug: 'special-cases',
    resource: 'SpecialCases',
    idField: 'specialCaseId',
    titleKey: 'lookupCatalogs.specialCases.title',
    hasCode: true,
    hasIsActive: false,
    hasAddress: false,
    nameMaxLength: 100,
    codeMaxLength: 10,
  },
  'void-reasons': {
    slug: 'void-reasons',
    resource: 'VoidReasons',
    idField: 'voidReasonId',
    titleKey: 'lookupCatalogs.voidReasons.title',
    hasCode: true,
    hasIsActive: false,
    hasAddress: false,
    nameMaxLength: 100,
    codeMaxLength: 20,
  },
  warehouses: {
    slug: 'warehouses',
    resource: 'Warehouses',
    idField: 'warehouseId',
    titleKey: 'lookupCatalogs.warehouses.title',
    hasCode: false,
    hasIsActive: true,
    hasAddress: true,
    nameMaxLength: 100,
  },
  'warehouse-periods': {
    slug: 'warehouse-periods',
    resource: 'WarehousePeriods',
    idField: 'warehousePeriodId',
    titleKey: 'lookupCatalogs.warehousePeriods.title',
    hasCode: false,
    hasIsActive: false,
    hasAddress: false,
    nameMaxLength: 20,
    hasCloseAction: true,
  },
};
